#!/system/bin/sh
exec /data/adb/modules/ts_enhancer_extreme/bin/cmd_tool \
  /system/bin/app_process \
  -Djava.class.path=/data/adb/modules/ts_enhancer_extreme/service.apk \
  / \
  --nice-name=TSEET \
  com.dere3046.tseet.Main \
  "$@"
